# Generated by Django 3.0.6 on 2020-06-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=50)),
                ('rentalFee', models.IntegerField()),
                ('deposit', models.IntegerField()),
            ],
        ),
    ]
