# Generated by Django 3.0.6 on 2020-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STCService', '0002_result_gucnt_result_gudongcnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='average',
            name='id',
        ),
        migrations.RemoveField(
            model_name='result_gucnt',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='result_gucnt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='result_gudongcnt',
            name='id',
        ),
        migrations.AlterField(
            model_name='average',
            name='gu',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result_gucnt',
            name='gu',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result_gudongcnt',
            name='dong',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
