# Generated by Django 3.0.6 on 2020-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STCService', '0003_auto_20200603_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendChartData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('avg_rentalFee', models.IntegerField()),
                ('avg_deposit', models.IntegerField()),
            ],
        ),
    ]
