# Generated by Django 3.0.5 on 2020-05-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('areaCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('si', models.CharField(max_length=50)),
                ('gu', models.CharField(max_length=50)),
                ('dong', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataProcess.Member')),
                ('gender', models.CharField(max_length=1)),
                ('birth', models.CharField(max_length=4)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLight',
            fields=[
                ('lightId', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOffice',
            fields=[
                ('policeId', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('policeOfficeName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('houseNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pyeong', models.FloatField()),
                ('houseName', models.CharField(max_length=100)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentPlace',
            fields=[
                ('placeId', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('placeName', models.CharField(max_length=100)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Member')),
            ],
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('costRecord', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('rentalFee', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('houseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.HouseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('cctvId', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
    ]
