# Generated by Django 3.0.6 on 2020-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('areaCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('si', models.CharField(max_length=50)),
                ('gu', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='birth',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='age_range',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='money',
            field=models.IntegerField(null=True),
        ),
    ]
