# Generated by Django 3.0.6 on 2020-06-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacyId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pharmacyName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('parkId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parkName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('libraryId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('libraryName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('gymId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gymName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalFacilities',
            fields=[
                ('culturalFacilitiesId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('culturalFacilitiesName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertHall',
            fields=[
                ('concertHallId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('concertHallName', models.CharField(max_length=50)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Address')),
            ],
        ),
    ]
