# Generated by Django 3.0.5 on 2020-05-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0002_auto_20200518_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='memberInfo',
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='member',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='dataProcess.Member'),
        ),
    ]
