# Generated by Django 3.0.5 on 2020-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0004_auto_20200525_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrecord',
            name='costRecord',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
