# Generated by Django 3.0.5 on 2020-05-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0005_auto_20200526_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costrecord',
            old_name='costRecord',
            new_name='costRecordId',
        ),
    ]
