# Generated by Django 3.0.5 on 2020-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0008_auto_20200526_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costrecord',
            name='id',
        ),
        migrations.AddField(
            model_name='costrecord',
            name='costRecordId',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
