# Generated by Django 3.0.5 on 2020-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0009_auto_20200526_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrecord',
            name='costRecordId',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False),
        ),
    ]
