# Generated by Django 3.0.5 on 2020-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProcess', '0011_auto_20200526_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctv',
            name='cctvId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='policeoffice',
            name='policeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='securitylight',
            name='lightId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
